import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import ELRAWallet from "../models/ELRAWallet.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

class TransactionReportService {
  constructor() {
    this.reportsDir = path.join(__dirname, "../uploads/transaction-reports");
    this.ensureReportsDirectory();
  }

  ensureReportsDirectory() {
    if (!fs.existsSync(this.reportsDir)) {
      fs.mkdirSync(this.reportsDir, { recursive: true });
    }
  }

  /**
   * Generate transaction history PDF report
   */
  async generateTransactionReport(transactions, filters = {}, userInfo = {}) {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const fileName = `transaction_report_${timestamp}.pdf`;
      const filePath = path.join(this.reportsDir, fileName);

      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      this.generateReportContent(doc, transactions, filters, userInfo);

      const pdfBytes = doc.output("arraybuffer");
      fs.writeFileSync(filePath, Buffer.from(pdfBytes));

      return {
        fileName,
        filePath,
        url: `/uploads/transaction-reports/${fileName}`,
      };
    } catch (error) {
      console.error(
        "❌ [TRANSACTION REPORT SERVICE] Error generating PDF:",
        error
      );
      throw error;
    }
  }

  /**
   * Generate the PDF content
   */
  generateReportContent(doc, transactions, filters, userInfo) {
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;

    // Set watermark with ELRA branding (like payslips)
    doc.setGState(new doc.GState({ opacity: 0.05 }));
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(100);
    doc.text("ELRA", pageWidth / 2, pageHeight / 2, {
      align: "center",
      angle: 30,
      renderingMode: "fill",
    });

    // Reset opacity for rest of the content
    doc.setGState(new doc.GState({ opacity: 1 }));

    // Header with ELRA branding (matching payslip style)
    const elraGreen = [13, 100, 73];
    doc.setTextColor(elraGreen[0], elraGreen[1], elraGreen[2]);
    doc.setFontSize(32);
    doc.setFont("helvetica", "bold");
    doc.text("ELRA", pageWidth / 2, 25, { align: "center" });

    // Reset to black for subtitle
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "normal");
    doc.text("Wallet Transaction Report", pageWidth / 2, 35, {
      align: "center",
    });

    yPosition = 50;

    // Report metadata
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated on: ${new Date().toLocaleDateString("en-NG")}`,
      20,
      yPosition
    );
    doc.text(
      `Generated by: ${userInfo.name || "System"}`,
      pageWidth - 20,
      yPosition,
      { align: "right" }
    );
    yPosition += 8;

    doc.text(`Department: ${userInfo.department || "N/A"}`, 20, yPosition);
    doc.text(`Role: ${userInfo.role || "N/A"}`, pageWidth - 20, yPosition, {
      align: "right",
    });
    yPosition += 15;

    // Filters applied
    if (Object.keys(filters).length > 0) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Filters Applied:", 20, yPosition);
      yPosition += 8;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");

      if (filters.type) {
        doc.text(`• Transaction Type: ${filters.type}`, 25, yPosition);
        yPosition += 5;
      }
      if (filters.startDate) {
        doc.text(
          `• Start Date: ${new Date(filters.startDate).toLocaleDateString(
            "en-NG"
          )}`,
          25,
          yPosition
        );
        yPosition += 5;
      }
      if (filters.endDate) {
        doc.text(
          `• End Date: ${new Date(filters.endDate).toLocaleDateString(
            "en-NG"
          )}`,
          25,
          yPosition
        );
        yPosition += 5;
      }
      yPosition += 10;
    }

    // Summary statistics
    const totalTransactions = transactions.length;
    const totalDeposits = transactions
      .filter((t) => t.type === "deposit")
      .reduce((sum, t) => sum + t.amount, 0);
    const totalWithdrawals = transactions
      .filter((t) => t.type === "withdrawal")
      .reduce((sum, t) => sum + t.amount, 0);
    const currentBalance =
      transactions.length > 0 ? transactions[0].balanceAfter : 0;

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Summary Statistics:", 20, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`• Total Transactions: ${totalTransactions}`, 25, yPosition);
    yPosition += 5;
    doc.text(
      `• Total Deposits: NGN ${this.formatCurrency(totalDeposits)}`,
      25,
      yPosition
    );
    yPosition += 5;
    doc.text(
      `• Total Withdrawals: NGN ${this.formatCurrency(totalWithdrawals)}`,
      25,
      yPosition
    );
    yPosition += 5;
    doc.text(
      `• Current Balance: NGN ${this.formatCurrency(currentBalance)}`,
      25,
      yPosition
    );
    yPosition += 15;

    // Transaction table
    if (transactions.length > 0) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Transaction Details:", 20, yPosition);
      yPosition += 10;

      const tableData = transactions.map((transaction) => [
        new Date(transaction.date).toLocaleDateString("en-NG"),
        new Date(transaction.date).toLocaleTimeString("en-NG"),
        transaction.type.toUpperCase(),
        this.truncateText(
          (transaction.description || "N/A")
            .replace(/_/g, " ")
            .replace(/-/g, " "),
          30
        ),
        this.truncateText(transaction.reference || "N/A", 20),
        this.formatTransactionAmount(transaction),
        `NGN ${this.formatCurrency(transaction.balanceAfter)}`,
      ]);

      autoTable(doc, {
        head: [
          [
            "Date",
            "Time",
            "Type",
            "Description",
            "Reference",
            "Amount",
            "Balance",
          ],
        ],
        body: tableData,
        startY: yPosition,
        styles: {
          fontSize: 8,
          cellPadding: 3,
        },
        headStyles: {
          fillColor: [13, 100, 73], // ELRA green color (matching payslips)
          textColor: 255,
          fontStyle: "bold",
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
        columnStyles: {
          0: { cellWidth: 20 }, // Date
          1: { cellWidth: 15 }, // Time
          2: { cellWidth: 20 }, // Type
          3: { cellWidth: 40 }, // Description
          4: { cellWidth: 25 }, // Reference
          5: { cellWidth: 25 }, // Amount
          6: { cellWidth: 25 }, // Balance
        },
        margin: { left: 20, right: 20 },
      });

      yPosition = doc.lastAutoTable.finalY + 10;
    } else {
      doc.setFontSize(12);
      doc.setFont("helvetica", "italic");
      doc.text(
        "No transactions found for the specified criteria.",
        20,
        yPosition
      );
      yPosition += 10;
    }

    // Footer
    const footerY = pageHeight - 20;
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(
      "This report was generated by ELRA ERP System",
      pageWidth / 2,
      footerY,
      { align: "center" }
    );

    // Add page numbers only once
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 10, {
        align: "right",
      });
    }
  }

  /**
   * Format currency for display
   */
  formatCurrency(amount) {
    return new Intl.NumberFormat("en-NG", {
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount || 0);
  }

  /**
   * Format transaction amount with proper signs
   */
  formatTransactionAmount(transaction) {
    const amount = Math.abs(transaction.amount);
    const formattedAmount = this.formatCurrency(amount);

    switch (transaction.type) {
      case "deposit":
        return `+NGN ${formattedAmount}`;
      case "withdrawal":
        return `-NGN ${formattedAmount}`;
      case "allocation":
        return `NGN ${formattedAmount}`;
      default:
        return `NGN ${formattedAmount}`;
    }
  }

  /**
   * Truncate text to specified length
   */
  truncateText(text, maxLength) {
    if (!text || text.length <= maxLength) {
      return text;
    }
    return text.substring(0, maxLength - 3) + "...";
  }

  /**
   * Generate Word document report (using HTML to DOCX conversion)
   */
  async generateTransactionWordReport(
    transactions,
    filters = {},
    userInfo = {}
  ) {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const fileName = `transaction_report_${timestamp}.html`;
      const filePath = path.join(this.reportsDir, fileName);

      const htmlContent = this.generateWordReportHTML(
        transactions,
        filters,
        userInfo
      );
      fs.writeFileSync(filePath, htmlContent);

      return {
        fileName,
        filePath,
        url: `/uploads/transaction-reports/${fileName}`,
        htmlContent,
      };
    } catch (error) {
      console.error(
        "❌ [TRANSACTION REPORT SERVICE] Error generating Word report:",
        error
      );
      throw error;
    }
  }

  /**
   * Generate HTML content for Word export
   */
  generateWordReportHTML(transactions, filters, userInfo) {
    const totalTransactions = transactions.length;
    const totalDeposits = transactions
      .filter((t) => t.type === "deposit")
      .reduce((sum, t) => sum + t.amount, 0);
    const totalWithdrawals = transactions
      .filter((t) => t.type === "withdrawal")
      .reduce((sum, t) => sum + t.amount, 0);
    const currentBalance =
      transactions.length > 0 ? transactions[0].balanceAfter : 0;

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ELRA Wallet Transaction Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { color: #0d6449; font-size: 24px; margin-bottom: 10px; }
        .metadata { margin-bottom: 20px; font-size: 12px; color: #666; }
        .summary { background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .summary h3 { color: #0d6449; margin-bottom: 10px; }
        .filters { background-color: #fff3cd; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .filters h3 { color: #856404; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #0d6449; color: white; font-weight: bold; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .amount-positive { color: #27ae60; font-weight: bold; }
        .amount-negative { color: #e74c3c; font-weight: bold; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>ELRA Wallet Transaction Report</h1>
        <div class="metadata">
            <p><strong>Generated on:</strong> ${new Date().toLocaleDateString(
              "en-NG"
            )}</p>
            <p><strong>Generated by:</strong> ${userInfo.name || "System"}</p>
            <p><strong>Department:</strong> ${userInfo.department || "N/A"}</p>
            <p><strong>Role:</strong> ${userInfo.role || "N/A"}</p>
        </div>
    </div>

    ${
      Object.keys(filters).length > 0
        ? `
    <div class="filters">
        <h3>Filters Applied:</h3>
        <ul>
            ${
              filters.type
                ? `<li><strong>Transaction Type:</strong> ${filters.type}</li>`
                : ""
            }
            ${
              filters.startDate
                ? `<li><strong>Start Date:</strong> ${new Date(
                    filters.startDate
                  ).toLocaleDateString("en-NG")}</li>`
                : ""
            }
            ${
              filters.endDate
                ? `<li><strong>End Date:</strong> ${new Date(
                    filters.endDate
                  ).toLocaleDateString("en-NG")}</li>`
                : ""
            }
        </ul>
    </div>
    `
        : ""
    }

    <div class="summary">
        <h3>Summary Statistics:</h3>
        <ul>
            <li><strong>Total Transactions:</strong> ${totalTransactions}</li>
            <li><strong>Total Deposits:</strong> NGN ${this.formatCurrency(
              totalDeposits
            )}</li>
            <li><strong>Total Withdrawals:</strong> NGN ${this.formatCurrency(
              totalWithdrawals
            )}</li>
            <li><strong>Current Balance:</strong> NGN ${this.formatCurrency(
              currentBalance
            )}</li>
        </ul>
    </div>

    <h3>Transaction Details:</h3>
    ${
      transactions.length > 0
        ? `
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Type</th>
                <th>Description</th>
                <th>Reference</th>
                <th>Amount</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            ${transactions
              .map(
                (transaction) => `
                <tr>
                    <td>${new Date(transaction.date).toLocaleDateString(
                      "en-NG"
                    )}</td>
                    <td>${new Date(transaction.date).toLocaleTimeString(
                      "en-NG"
                    )}</td>
                    <td>${transaction.type.toUpperCase()}</td>
                    <td>${(transaction.description || "N/A")
                      .replace(/_/g, " ")
                      .replace(/-/g, " ")}</td>
                    <td>${transaction.reference || "N/A"}</td>
                    <td class="${
                      transaction.type === "deposit"
                        ? "amount-positive"
                        : transaction.type === "withdrawal"
                        ? "amount-negative"
                        : ""
                    }">
                        ${this.formatTransactionAmount(transaction)}
                    </td>
                    <td>NGN ${this.formatCurrency(
                      transaction.balanceAfter
                    )}</td>
                </tr>
            `
              )
              .join("")}
        </tbody>
    </table>
    `
        : "<p><em>No transactions found for the specified criteria.</em></p>"
    }

    <div class="footer">
        <p>This report was generated by ELRA ERP System</p>
        <p>Generated on ${new Date().toLocaleString("en-NG")}</p>
    </div>
</body>
</html>
    `;
  }

  /**
   * Generate CSV report
   */
  async generateTransactionCSVReport(
    transactions,
    filters = {},
    userInfo = {}
  ) {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const fileName = `transaction_report_${timestamp}.csv`;
      const filePath = path.join(this.reportsDir, fileName);

      const csvContent = this.generateCSVContent(
        transactions,
        filters,
        userInfo
      );
      fs.writeFileSync(filePath, csvContent);

      return {
        fileName,
        filePath,
        url: `/uploads/transaction-reports/${fileName}`,
        csvContent,
      };
    } catch (error) {
      console.error(
        "❌ [TRANSACTION REPORT SERVICE] Error generating CSV report:",
        error
      );
      throw error;
    }
  }

  /**
   * Generate CSV content
   */
  generateCSVContent(transactions, filters, userInfo) {
    const headers = [
      "Date",
      "Time",
      "Type",
      "Description",
      "Reference",
      "Amount",
      "Balance",
    ];

    const rows = transactions.map((transaction) => [
      new Date(transaction.date).toLocaleDateString("en-NG"),
      new Date(transaction.date).toLocaleTimeString("en-NG"),
      transaction.type.toUpperCase(),
      `"${(transaction.description || "N/A")
        .replace(/_/g, " ")
        .replace(/-/g, " ")}"`,
      transaction.reference || "N/A",
      this.formatTransactionAmount(transaction),
      `NGN ${this.formatCurrency(transaction.balanceAfter)}`,
    ]);

    const csvRows = [headers, ...rows];
    return csvRows.map((row) => row.join(",")).join("\n");
  }
}

export default TransactionReportService;
